
# FIXME issue 131
# [tool.mypy]
# ignore_missing_imports = true
# strict = true
# # If certain strict config options are too pedantic for a project,
# # disable them selectively here by setting to false.

[tool.black]
skip-string-normalization = true
# # Use the more relaxed max line length permitted in PEP8.
line-length = 99
target-version = ["py38", "py39", "py310"]
# # black will automatically exclude all files listed in .gitignore
# # If you need to exclude additional folders, consider using extend-exclude to avoid disabling the
# # default .gitignore behaviour.
extend-exclude="(data|axelera/app/fmzoo)"

# FIXME issue 128
[tool.isort]
profile = "black"
line_length = 99
force_sort_within_sections = true
# Inform isort of paths to import names that should be considered part of the "First Party" group.
src_paths = ["axelera", "ax_models", "ax_datasets", "ax_models/yolo/models"]
skip_gitignore = true
# If you need to skip/exclude folders, consider using skip_glob as that will allow the
# isort defaults for skip to remain without the need to duplicate them.
skip_glob = ["data/*"]
known_third_party = ["torch", "torchvision", "numpy", "PIL", "onnx", "onnxruntime"]

[tool.pytest.ini_options]
testpaths = [
    "tests",
    "internal_tools_tests",
    "llm_tests",
]
pythonpath = [".", "internal_tools"]
filterwarnings = """\
    ignore:.*call to `pkg_resources.declare_namespace.*:DeprecationWarning
    ignore:.*pkg_resources is deprecated as an API.*:DeprecationWarning
"""
